### ISSUE TITLE
Ramen Noodle synth yield lower than it should be

### ISSUE THREAD

**Issue by almuth150** [Delkathus/SNFFXIBugTracker#12]
**_I have:_**

- [x] checked the commit log to see if the issue has been resolved since my server was last updated
- [x] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker/issues/) to see if the issue has already been opened.

**_In Game Name_** **:** 
Almuth

**_Additional Information_** (Steps to reproduce/Expected behaviour. Dev's may request additional info so please give as much as you can) **:**
The synth for Ramen Noodles is yielding 1, regardless of NQ or HQ. It should be yielding 4/6/8/10 per synth. It appears to be a problem on current topaz as well. https://ffxiclopedia.fandom.com/wiki/Ramen_Noodles

**Comment by Delkathus** [comment]
This issue has a correction submitted, pending merge.

**Comment by Delkathus** [comment]
PR Merged and will be available next update.
