### ISSUE TITLE
Lindwurm skin drop rate is far too low

### ISSUE THREAD

**Issue by almuth150** [Delkathus/SNFFXIBugTracker#13]
**_I have:_**

- [x] checked the commit log to see if the issue has been resolved since my server was last updated
- [x] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker/issues/) to see if the issue has already been opened.

**_In Game Name_** **:** 
Almuth

**_Additional Information_** (Steps to reproduce/Expected behaviour. Dev's may request additional info so please give as much as you can) **:**
Lindwurm is supposed to be able to drop "multiple skins", and presumably at a much better rate than the current 11% chance for a single skin. I'm not exactly sure what it should be at though, maybe something like the rate and amounts for Yowie skins?
https://ffxiclopedia.fandom.com/wiki/Lindwurm
http://ffxidb.com/zones/205/lindwurm

**Comment by tristamgreen** [comment]
this has been increased
