### ISSUE TITLE
Beast and Drachen rolls do not affect pet ranged stats

### ISSUE THREAD

**Issue by almuth150** [Delkathus/SNFFXIBugTracker#16]
**_I have:_**

- [x] checked the commit log to see if the issue has been resolved since my server was last updated
- [x] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker/issues/) to see if the issue has already been opened.

**_In Game Name_** **:** 
Almuth

**_Additional Information_** (Steps to reproduce/Expected behaviour. Dev's may request additional info so please give as much as you can) **:**
Those rolls are supposed to increase both melee and ranged stats, according to both the in-game roll description and bg-wiki. However, it only increases the melee stats.

**Comment by almuth150** [comment]
Seems to be missing in the roll effect scripts?

https://github.com/project-topaz/topaz/blob/release/scripts/globals/effects/beast_roll.lua
https://github.com/project-topaz/topaz/blob/release/scripts/globals/effects/drachen_roll.lua

**Comment by almuth150** [comment]
Beast Roll was fixed on topaz in this commit: https://github.com/project-topaz/topaz/commit/b3b62a109ecf6493b0eba81df84c1a1ca6b126fe

Drachen Roll is not fixed on topaz as of this comment, however. Near identical remedy though.

**Comment by Acrossy** [comment]
I sent the update request to Topaz for Beast Roll and it was already merged! So that one is covered!
