### ISSUE TITLE
SMN-only Pet-Specific Items missing Mods/Latents

### ISSUE THREAD

**Issue by tristamgreen** [Delkathus/SNFFXIBugTracker#17]
Summoner-only Pet Specific items in the list below do not have any, or some, of their pet-specific pet mods.

These are the affected items and the mods that are missing:

Karura Hachigane (itemid 16154)
-- Attack Bonus (Garuda) (Pet Attack+10)
-- Defense Bonus (Garuda) (Pet Def. +10)

Evoker's Gages (itemid 14960)
-- Attack Bonus (Leviathan) (Pet Attack +10)

Morana's Pigaches (itemid 11408)
-- Enhances Magic Accuracy (Shiva) (Pet Macc +10?) (assuming based on other contemporary items)

Fenrir's Crown (itemid 11496)
-- Enhances Accuracy (Fenrir) (Pet Acc +10?) (assuming based on other contemporary items)

**Comment by almuth150** [comment]
Adding to the list of conditional pet-boosting items:

Affinity earring (id 16031) - latent triggered by someone else in party being PUP, gives pet atk+ 6~7 according to a comment on ffxiah (neither wiki listed the amount of the bonus).

Fidelity earring (id 16022) - latent triggered by someone else in the party being BST, gives pet acc +3 according to bgwiki.

Incidentally, I recall a recent commit on topaz adding the NM that drops the Affinity earring, so it's currently not obtainable on SN once the AH runs out.
