### ISSUE TITLE
Accuracy issue for spells of a skill boosted by Light/Dark arts on a job that does not natively have the skill

### ISSUE THREAD

**Issue by almuth150** [Delkathus/SNFFXIBugTracker#18]
**_I have:_**

- [x] checked the commit log to see if the issue has been resolved since my server was last updated
- [x] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker/issues/) to see if the issue has already been opened.

**_In Game Name_** **:** 
Almuth

**_Additional Information_** (Steps to reproduce/Expected behaviour. Dev's may request additional info so please give as much as you can) **:**
Example, using Dark Arts on WHM/SCH and casting Aspir, while I do get more mp taken than say, RDM/BLM, I get resisted far more often. A quick test vs. a level 77 crab got me 2 resists in 20 casts on RDM/SCH, and said resists being only half, while on WHM/SCH I'd rarely get unresisted, and most resists were more severe.

On WHM I had 282 stated dark magic skill with arts active, +59 mag acc from gear, +50 mag acc from crepe, and 110 total INT. On RDM I had 252 stated dark magic skill, +48 mag acc from gear, +50 mag acc from crepe, and 106 total INT. I should most certainly expect higher accuracy from WHM/SCH with the stated information, yet the results show otherwise.

**Comment by TrueSalmon** [comment]
I've also had doubts about /sch working for jobs without that innate skill and I'm not alone in that. Curious to see what comes of this.

**Comment by almuth150** [comment]
I don't really know how to get any more information without having my own test server and getting some exact numbers that way, since magic accuracy is entirely invisible to players. All I can tell is that it seems to use the proper skill level for calculating damage, but seemingly not accuracy.

**Comment by Delkathus** [comment]
When we do the topaz merge this might be resolved as there was work done on correcting a plethora of formulae etc.

**Comment by almuth150** [comment]
Did some testing post update, this issue was not resolved by the merge.
