### ISSUE TITLE
Certain pet-boosting foods are missing their stated modifiers

### ISSUE THREAD

**Issue by almuth150** [Delkathus/SNFFXIBugTracker#23]
**_I have:_**

- [x] checked the commit log to see if the issue has been resolved since my server was last updated
- [x] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker/issues/) to see if the issue has already been opened.

**_In Game Name_** **:** 
Almuth

**_Additional Information_** (Steps to reproduce/Expected behaviour. Dev's may request additional info so please give as much as you can) **:**
Grape Daifuku (+1) - missing the STR, attack%, and ranged attack% boost for both players and pets
Bean Daifuku (+1) - missing the defense% bonus for pets

**Comment by Delkathus** [comment]
Trist submitted the fix for this and is pending topaz merge
