### ISSUE TITLE
Pets can't be used in The Celestial Nexus

### ISSUE THREAD

**Issue by almuth150** [Delkathus/SNFFXIBugTracker#24]
**_I have:_**

- [s] checked the commit log to see if the issue has been resolved since my server was last updated
- [s] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker/issues/) to see if the issue has already been opened.

**_In Game Name_** **:** 
Almuth

**_Additional Information_** (Steps to reproduce/Expected behaviour. Dev's may request additional info so please give as much as you can) **:**
Pets cannot be called in that zone, period. Makes doing the final ZM battle annoying for people on those jobs, especially when they don't know about this issue.

**Comment by Delkathus** [comment]
Will be addressed soon as we are looking for areas for different pvp zones.
