### ISSUE TITLE
Inventory becomes locked after using Porter Moogle

### ISSUE THREAD

**Issue by tristamgreen** [Delkathus/SNFFXIBugTracker#25]
Upon using a Porter Moogle for storage or retrieval of items, player inventory becomes locked until the player zones.  Items cannot be dropped, they cannot be shifted to Mog Safe or any other storage, and items cannot be retrieved out of any storage.

This issue fixes itself when the player zones.

**Comment by TrueSalmon** [comment]
Is this related to the retrieve-more-than-2-items-from-porter-crashes-you bug?

**Comment by tristamgreen** [comment]
Unsure.  I know that Treasury causes that problem, and unloading Treasury or disabling a part of it (i forget, but think it's autosort?) fixes that issue.  This one doesn't crash you, it just causes your inventory to be essentially unusable.

**Comment by Delkathus** [comment]
This was overlooked during the dupe patch and a pr was merged to correct this. Just need server rebuild to push it live.

Will close this once server is updated.

**Comment by tristamgreen** [comment]
Word, closing in that case. Spread the word this will be fixed next update!
