### ISSUE TITLE
Fields/Grounds of valor points hard to gain

### ISSUE THREAD

**Issue by Cabshank** [Delkathus/SNFFXIBugTracker#4]
Since the changes to pages being once a day, its harder to build up your balance of tabs for FoV/GoV book buffs. I find myself at a net loss of tabs since we have done the new one per game day rule(even though I do a fair amount of pages while exping). My suggestion is just to buff the number of tabs per page across the board so newbies can gain tabs and use the buffs for missions and other random adventuring when you might need circumspection or other buffs

**Comment by TrueSalmon** [comment]
I'm not sure this is that much of an issue. My brother started a few months ago and is up to 1k+ tabs already. You gotta do a page now and then, sure, but that's the point.
