### ISSUE TITLE
Limbus battle music after win/timeout

### ISSUE THREAD

**Issue by ba3oo** [Delkathus/SNFFXIBugTracker#5]
**_I have:_**

- [x] confirmed that I can reproduce this error, if possible. (Provide SS' or Video as proof below).
- [x] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

basicly after limbus either apolyon or temanos ends by exiting portal or being timed out battle music would still be playing as if u didnt leave battle area . happens everytime. BCNM tag would wear off though normaly  so no issues there.

best regards

**Comment by Delkathus** [comment]
This will be resolved in the Topaz Merge, but for the time being the music shall play lol
