### ISSUE TITLE
Porter Mog kicks you out after retreiving items

### ISSUE THREAD

**Issue by ba3oo** [Delkathus/SNFFXIBugTracker#6]
**_I have:_**

- [X] confirmed that I can reproduce this error, if possible. (Provide SS' or Video as proof below).
- [X] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker) to see if the issue has already been opened.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

basicly as title says, i retrive full relic set and boom crash, not first time. its not too bad but jjust putting it out there

**Comment by Delkathus** [comment]
Is it for specific slips? Specific sets? Is it consistent crash for each use? Is it a crash only for you? Is it a crash for server? Do you still receive the set after retrieving the set?

**Comment by ba3oo** [comment]
it worked on any set, but i notice it happens when  i draw 5+ items, only i crash and its instant kicked out not like d/c or screen freeze

**Comment by Delkathus** [comment]
Recent reports stating that treasurer may be causing the issues. Further confirmation required.

**Comment by TrueSalmon** [comment]
According to Arnd and Madamewardu, this could be due to Treasury's autostack function. **//treasury autostack off** seems to do the trick.

**Comment by tristamgreen** [comment]
Discovered that the autostack function in the treasury plugin causes this.

Try this:
//treasury autostack off

As per Arnd, Madamewardu, and Tristamgreen
