### ISSUE TITLE
Ix aern depop

### ISSUE THREAD

**Issue by ba3oo** [Delkathus/SNFFXIBugTracker#7]
**_I have:_**

- [NO] confirmed that I can reproduce this error, if possible. (Provide SS' or Video as proof below).
- [X] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker) to see if the issue has already been opened.

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

ok so its not really somthing am going to try to reproduce >.> cause its a lot of work but happend once so i thought should report. i dont have any SS cause its somthing that happend suddenly. we were fighting Ix Aern Drk and on 8th kill he RRed > Depop right away, i have a guess to why this happend, one member HPed after he RRed and i think he might have had hate from ix aern when he rose... so when he HPed he just sudden depop.. i dont know if this is bug or normal beahivor but its defnitly annoying after spending so much time killing it 8 times ... ( i soloed first kill )  but thought i should post this here for future people to not make ssame mistake. and hope we can get a resuce on this :D

**Comment by Delkathus** [comment]
It can be a one off and a rare occurrence will keep this open in the event it does occur again. If it does then make another comment with more detailed information on how to recreate it.
