### ISSUE TITLE
Beastmaster Shattering Stars

### ISSUE THREAD

**Issue by Arnd-SN** [Delkathus/SNFFXIBugTracker#8]
**_I have:_**

- [X] confirmed that I can reproduce this error, if possible. (Provide SS' or Video as proof below).
- [X] searched existing issues (https://github.com/Delkathus/SNFFXIBugTracker) to see if the issue has already been opened.

Fought Maat three separate times on BST66 and encountered the same errors. Once engaged, I was no longer able to utilize any JAs such as Reward, Snarl, or Ready.

![Maat Fight](https://user-images.githubusercontent.com/66708123/86601724-49dd5480-bf67-11ea-8fe3-b244f666a047.png)

**Comment by Delkathus** [comment]
This should be resolved in the Topaz Merge
